### PR TITLE
[WIP] Implementing Sequel ORM support

### PR DESCRIPTION
**Pull request by francois**
Hello @bogdan. This is the __beginning__ of Sequel support. I have not run the tests against the Sequel code yet, and I only implemented the minimum amount of code possible to get Datagrid running for one screen I have.

`AbstractDriver` has no documentation. For me, this makes it difficult to fully implement the Sequel driver, since I don't know exactly what the methods are supposed to be doing.

What does the `#default_order` method do? It seems to be the default order for the column, but I'm not sure. Returning nil seemed like a safe option.

### CODE REVIEW

**Comment by bogdan** [comment]
Yes, there is no doc because new drivers are not so common. Maybe we will write some later.

`default_order` suppose to return a default value for `order` column option when it is not specified. `nil` methods that column ordering is disabled unless explicitly specified.

The ActiveRecord's implementation is slightly tricky because it is better to pass `users.created_at` as an `ORDER BY` SQL argument than `created_at` because it is safe to column name collision in joined tables. And default order is only applicable when column exist in database.

Other ORMs don't have this problem but sequel may have it.

It is not a big deal to implement them all because I am sure there will be just different method names than ActiveRecord for thing that do exactly the same in Sequel.

This is not ready yet of course. I can handle it myself later this week or let you finish it.

**Comment by francois** [comment]
I'd like to work on this branch a bit more. In order to accept this patch, you will require tests. What other things would you require as well?

How much experience do you have with Sequel?

**Comment by bogdan** [comment]
Tests are essencial... they are even more valuable then implementation.

My experience with Sequel is exactly zero.

Here what I've got by raping it's documentation. Maybe it will point you to the right direction.

https://gist.github.com/f4a1e65632d046e7f6cc

**Comment by francois** [comment]
Thanks! I'll review and write relevant tests.

**Comment by bogdan** [comment]
I've implemented a full sequel support in master and wrote tests. It should be fine now, but still requires some on-live-app testing. You can try it from master if you want and let me know if there are any problems.

**Comment by francois** [comment]
Hi, sorry for not working on this sooner. I actually never needed more than what I had implemented. I�ll switch to master and will use it in my app.

Thanks!

**Pull request merged**
