### PR TITLE
Add composite filter for Time

### PR DESCRIPTION
**Pull request by markedmondson**
Replicate `date_range_filter(:attr)` behaviour for a time based composite filter.

Additionally DRY the filter generating method.

### CODE REVIEW

**Comment by bogdan** [comment]
Sorry, but I consider using multiple filters to express range a deprecated strategy. You should use the following instead:

``` ruby
filter(:attr, :datetime, range: true)
```

Is there any reason it doesn't fit your needs? 

I thought I cleaned up all usages of `date_range_filter` from docs. Did you find any I forgot about?

**Comment by markedmondson** [comment]
Actually these are really useful for using your gem with Rails FormHelper as it's then possible to generate the search form like so:

    form_for @collection do |f|
        f.text_field :from_created_at
        f.text_field :to_created_at
    end

This becomes valuable because the FormHelper tries to set the default value by calling the field as a method on the form object to get the default value, eg: @collection.from_created_at

With the range based filters you'd need something like:

    form_for @collection do |f|
        f.fields_for :completed_at do |c|
            c.text_field :from
            c.text_field :to
        end
    end

It could be done without these composite filters assuming then that the collection returns a struct or something that responds to `from` or `to`. Since the range only takes an array, there's no way currently to reference these and thus the form tries to call @collection.completed_at.from (which doesn't exist), nor do I think it's possible to generate the fields for the array in any way.

Open to feedback on a better method, it's just the from_ and to_ filters are a lot easier to work with. Maybe an example of using the range in your demo would straighten me out?

**Comment by bogdan** [comment]
The problem with composite filters is that they are completely not semantic.
I would feel myself more confident with:

``` ruby
grid.completed_at = 10.days.ago..Time.now
# rather than
grid.from_completed_at = 10.days.ago
grid.to_completed_at = Time.now
```

Also I like the true range interface more: 

img
 
Demo is in place: http://datagrid.herokuapp.com/user_reports

The following should just work fine:

``` ruby
form_for @collection do
  c.datagrid_filter :completed_at
end
```

Also you may try to run `rake datagrid:copy_partials` and modify `_range_filter.html.erb`. It will help you with other gems integration.

**Comment by markedmondson** [comment]
Ah, I see, thank you. You have a FormBulder that provides the inputs for the range. We're actually using Formtastic, so that's I guess where this falls down.

I'll try plugging your FormBuilder into Formtastic but that probably would need a separate (probably not so hard) piece. In the meantime we'll have to stick to using the composite filters.

**Comment by PirunSeng** [comment]
@bogdan ! Sorry if I'm asking in wrong place as I don't where to post my question.
Would you please tell me which datepicker is used for date range filter?
I've tried datepicker of jQuery-UI, but it seems not work really well for my case. Sometimes, the date input doesn't keep the chosen date after I click the search button.
Any help please?

**Comment by bogdan** [comment]
@PirunSeng "Sometimes" feels really strange. Please create a new issue with your question and provide more information: grid, controller and form source code.

**Comment by PirunSeng** [comment]
@bogdan ! I don't think it's an issue of the gem, that is why I didn't create one.
I use jQuery UI for the datepicker, but I'm not familiar with it enough so that I am going into problem.
Anyway, my problem is solved now, thanks.

Here is my previous code:
$('.datepicker').datepicker();

I solved my problem by just adding format option to the function:
$('.datepicker').datepicker({ dateFormat: 'yy-mm-dd' });

It maybe because of the date format of my record.

An answer from the link is really helpful for my case:
http://stackoverflow.com/questions/25576234/why-is-my-date-out-of-range-for-some-dates-but-not-others

**Comment by bogdan** [comment]
Between discussing your not-gem issue here and in new ticked - I would prefer a new ticket.

You may control datagrid's date format also: https://github.com/bogdan/datagrid/wiki/Configuration

**Comment by PirunSeng** [comment]
Is is format for the grid column or grid filter?
Anyway, I would ask how datagrid implements the datepicker.
Thanks.

**Comment by bogdan** [comment]
Format is for date filter.  Column formating can be done manually via `format`.

**Comment by PirunSeng** [comment]
@bogdan ! Thanks.
What about the datepicker? How is it implemented in the datagrid?

**Comment by bogdan** [comment]
@PirunSeng it is not implemented in datagrid. You just attach a datepicker you want to an input with one line of code. See example here: http://datagrid.herokuapp.com/user_reports

**Comment by PirunSeng** [comment]
@bogdan ! Oh, I see.
Thank you very much for your help.

**Comment by bogdan** [comment]
@markedmondson closing for now... respond if you have anything to say.

**Pull request closed without merging**
